version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.24.0
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - askida-kitap-network
    depends_on:
      - app
      - db

  app:
    image: 'askida-kitap'
    container_name: askida-kitap-app
    build:
      context: .
    ports:
      - ":8080"
    networks:
      - askida-kitap-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/askidakitap
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db


  db:
    image: postgres:15.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=askidakitap
    volumes:
      - ./docker/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - askida-kitap-network


networks:
  askida-kitap-network: