version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.24.0
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - askida-kitap-network
    depends_on:
      - app
      - db

  app:
    image: 'askida-kitap'
    container_name: askida-kitap-app
    build:
      context: .
    command: sh ./docker/bash/run.sh
    volumes:
      - ./:/askida-kitap
      - ./docker/app/.m2:/root/.m2
    working_dir: /askida-kitap
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - askida-kitap-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/askidakitap
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db


  db:
    image: postgres:15.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=askidakitap
    volumes:
      - ./docker/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - askida-kitap-network

  #REDIS
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      - askida-kitap-network
    restart: always


networks:
  askida-kitap-network: