version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.24.0
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/configure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - askida-kitap-network
    depends_on:
      - app
      - db

  app:
    image: 'askida-kitap'
    container_name: askida-kitap-app
    build:
      context: .
    command: sh ./docker/configure/bash/run.sh
    volumes:
      - ./:/askida-kitap
      - ./docker/volumes/app/.m2:/root/.m2
    working_dir: /askida-kitap
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - askida-kitap-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/askidakitap
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db


  db:
    image: postgres:15.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=askidakitap
    volumes:
      - ./docker/volumes/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - askida-kitap-network

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    volumes:
#      - ./docker/volumes/pgadmin/pgadmin-data:/var/lib/pgadmin
#    networks:
#      - askida-kitap-network

  #REDIS
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      - askida-kitap-network
    restart: always



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - askida-kitap-network
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - askida-kitap-network
    restart: always


networks:
  askida-kitap-network: